// Code generated by "doxxer . -h"; DO NOT EDIT.

/*
Doxxer is a tool that generates documentation for command line applications.

Usage:

	doxxer [-o output] <package> [arguments...]

Flags:

	-o output
	  	Write output to file (default "doc.go")

Typically, arguments are specified using "//go:generate" directives, which are
passed verbatim to "go run" to generate output. Output is then passed through
"gofmt" and finally written to a file, which by default is doc.go.

The following example demonstrates generating documentation for an application
that makes use of the standard flag package:

Example:

	//go:generate doxxer . -h
	package main

If doxxer is called directly from the command line, the $GOROOT and $GOPACKAGE
environment variables must be defined as documented in "go help generate".

Report issues to https://github.com/sstallion/go-tools/issues.
*/
package main
